name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Show environment variables
      - name: Check Env
        run: echo "CSV_URL=$CSV_URL"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run MLflow project (point to folder MLproject/)
      - name: Run MLflow project
        run: mlflow run MLproject --env-manager=local

      # Upload mlruns as artifact
      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLproject/mlruns/
