name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLproject/requirements.txt
          pip install mlflow

      # Clean mlruns before run
      - name: Clean mlruns
        run: rm -rf MLproject/mlruns

      # Run MLflow project
      - name: Run MLflow project
        run: mlflow run MLproject --env-manager=local

      # Upload trained model as artifact
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLproject/mlruns
