name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: echo "CSV_URL=$CSV_URL"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Clean old mlruns
        run: rm -rf mlruns

      - name: Run MLflow project
        run: mlflow run MLproject --env-manager=local

      - name: Collect latest run ID
        id: latest_run
        run: |
          LATEST_RUN=$(ls -td mlruns/*/*/ | head -1)
          echo "LATEST_RUN=$LATEST_RUN" >> $GITHUB_ENV

      - name: Generate summary markdown
        run: |
          SUMMARY_FILE=summary.md
          echo "# MLflow Run Summary" > $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "## Parameters" >> $SUMMARY_FILE
          cat $LATEST_RUN/params/* 2>/dev/null | sed 's/^/- /' >> $SUMMARY_FILE || echo "_No params found_" >> $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "## Metrics" >> $SUMMARY_FILE
          cat $LATEST_RUN/metrics/* 2>/dev/null | sed 's/^/- /' >> $SUMMARY_FILE || echo "_No metrics found_" >> $SUMMARY_FILE

      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-summary
          path: summary.md
          
